import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import {
  // AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiFillInstagram
} from 'react-icons/ai'
import Image from 'next/image'
import PrathamMathurProfilePic from '../public/assets/PrathamMathurProfilePic-removebg-preview.png'
// import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import allProjectsData from '../AllImages'
import { useState, useEffect } from 'react'
import AOS from 'aos'
import 'aos/dist/aos.css' // You can also use <link> for styles

export default function Home () {
  const [darkMode, setDarkMode] = useState(true)
  const [projects, setProjects] = useState([])

  useEffect(() => {
    setProjects(allProjectsData)
    AOS.init()
  }, [])

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Pratham Mathur Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <header className='py-10 mb-10 flex justify-between dark:text-white'>
          <h1 className='text-xl font-burtons'>Developed by Pratham Mathur</h1>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill
                onClick={() => setDarkMode(!darkMode)}
                className='cursor-pointer text-2xl'
              />
            </li>
            <li>
              <a
                className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'
                href='https://drive.google.com/file/d/1sGQXU5_GxGJpI7DhncZfMVSngtbmP0Dl/view'
              >
                Resume
              </a>
            </li>
          </ul>
        </header>
        {/* Home Section */}
        <section className='min-h-screen'>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>
              Pratham Mathur
            </h2>
            <h3 className='text-2xl py-2 dark:text-white  md:text-3xl'>
              FrontEnd Developer
            </h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-200'>
              I have a good amount of experience and knowledge working with
              <span className='text-teal-500'> MERN </span>
              Stack and can rapidly learn new technologies. I'm searching for an
              opportunity to work with a variety of technologies.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillLinkedin
              cursor='pointer'
              onClick={() =>
                (window.location.href =
                  'https://www.linkedin.com/in/pratham-mathur-5b99681ab/')
              }
              className='hover:fill-blue-500'
            />
            <AiFillGithub
              cursor='pointer'
              onClick={() =>
                (window.location.href = 'https://github.com/PrathamMathur11')
              }
              className='dark:hover:fill-red-100  hover:fill-black'
            />
            <AiFillInstagram
              cursor='pointer'
              onClick={() =>
                (window.location.href =
                  'https://www.instagram.com/pratham_mathur11/')
              }
              // fill='#E4405F'
              className='hover:fill-pink-600'
            />
          </div>
          <div
            data-aos='fade-in'
            className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'
          >
            <Image
              src={PrathamMathurProfilePic}
              style={{
                objectFit: 'cover',
                scale: '1.3',
                filter: 'drop-shadow(-7px 4px 4px black)'
              }}
              layout='fill'
              // objectFit='cover'
              alt='pp'
            />
          </div>
        </section>
        {/* Skills Section */}
        <section>
          <div>
            <h1 className='text-4xl py-1 dark:text-white'>Skills</h1>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200'>
              Furthermore, I have experience working in a fast-paced yet
              <span className='text-teal-500'> agile work setting</span>, and I
              appreciate teamwork and maintaining a healthy work environment.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div
              data-aos='fade-right'
              data-aos-delay='250'
              className='text-center cursor-pointer shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white hover:bg-slate-100 dark:hover:bg-slate-100'
            >
              <Image
                src={design}
                width={100}
                height={100}
                className='m-auto'
                alt=''
              />
              <h3 className='text-lg font-medium pt-8 pb-2  '>
                FRONT END STACK
              </h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design Tools I Use</h4>
              <p className='text-gray-800 py-1'>ReactJS</p>
              <p className='text-gray-800 py-1'>Bootstrap</p>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Material UI</p>
              <p className='text-gray-800 py-1'>TailwindCSS</p>
            </div>
            <div
              data-aos='fade-in'
              data-aos-delay='250'
              className='text-center cursor-pointer shadow-lg p-10 rounded-xl my-10  flex-1 dark:bg-white hover:bg-slate-100 dark:hover:bg-slate-100'
            >
              <Image
                src={code}
                width={100}
                height={100}
                className='m-auto'
                alt=''
              />
              <h3 className='text-lg font-medium pt-8 pb-2 '>BACK END STACK</h3>
              <p className='py-2'>
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className='py-4 text-teal-600'>Tools I Use</h4>
              <p className='text-gray-800 py-1'>NodeJS</p>
              <p className='text-gray-800 py-1'> ExpressJS</p>
              <p className='text-gray-800 py-1'>MongoDB</p>
              <p className='text-gray-800 py-1'>FIREBASE</p>
              <p className='text-gray-800 py-1'>SQL</p>
            </div>
            <div
              data-aos='fade-left'
              data-aos-delay='250'
              className='text-center cursor-pointer shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white hover:bg-slate-100 dark:hover:bg-slate-100'
            >
              <Image
                src={consulting}
                width={100}
                height={100}
                className='m-auto'
                alt=''
              />
              <h3 className='text-lg font-medium pt-8 pb-2 '>OTHER SKILLS</h3>
              <p className='py-2'>Some Soft but very Important skills</p>
              <h4 className='py-4 text-teal-600'>Tech Skills</h4>
              <p className='text-gray-800 py-1'>C / C++ / Java </p>
              <p className='text-gray-800 py-1'>HTML / CSS / JavaScript</p>
              <p className='text-gray-800 py-1'>Git / GitHub</p>
              <h4 className='py-4 text-teal-600'>Soft Skills</h4>
              <p className='text-gray-800 py-1'>
                Analytical / Problem Solving Skills
              </p>
              <p className='text-gray-800 py-1'>Team Work</p>
              <p className='text-gray-800 py-1'>Leadership</p>
            </div>
          </div>
        </section>
        {/* Personal Projects Section */}
        <section>
          <div className=''>
            <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200'>
              I have a good amount of experience and knowledge working with{' '}
              <span className='text-teal-500'>MERN </span>
              Stack and can rapidly learn new technologies. I'm searching for an
              opportunity to work with a variety of technologies.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            {projects
              .sort(() => Math.random() - 0.5)
              .map((item, index) => {
                let direct = 'right'
                if (index % 2 == 0) {
                  direct = 'right'
                } else {
                  direct = 'left'
                }
                return (
                  <div
                    className='basis-1/3 flex-1 rounded-lg hover:scale-105 transition-all'
                    key={index}
                    // style={{ boxShadow: 'rgb(0 0 0 / 25%) 0px 0px 15px' }}
                  >
                    <div
                      data-aos={`fade-up-${direct}`}
                      data-aos-delay={index * 150}
                      className='relative container'
                    >
                      <Image
                        src={item.imageURL}
                        alt='images'
                        className='rounded-lg object-fill grayscale hover:grayscale-0 hover:shadow-lg cursor-pointer md:-skew-y-6'
                        width={'100%'}
                        height={'100%'}
                        layout='responsive'
                        onClick={() =>
                          (window.location.href = `${item.redirectLink}`)
                        }
                      />
                      <span className='absolute names md:-skew-y-6 left-0 bg-teal-500 text-white w-auto h-auto rounded px-4 py-0.5'>
                        {item.title}
                      </span>
                    </div>
                  </div>
                )
              })}
          </div>
        </section>
        <footer className='dark:text-white mt-8'>Footer</footer>
      </main>
    </div>
  )
}
